import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

import localFont from "next/font/local";

import StyledComponentsRegistry from "@/lib/registry";

import AppBackground from "@/components/Background";
import GlobalStyles from "@/components/GlobalStyles";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Trinh The Son",
  description: "Generated by create next app",
};

const wotfard = localFont({
  src: [
    {
      path: "../../public/fonts/Circular-Book.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Circular-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Circular-Bold.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  display: "fallback",
  preload: false,
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={wotfard.className}
    >
      <head>
        <link
          href="/images/favicon.png"
          rel="icon"
          type="image/png"
        />
      </head>
      <StyledComponentsRegistry>
        <AppBackground>
          <MaxWidthWrapper>
            <Header />
            <Hero />
            {children}
            <Footer/>
          </MaxWidthWrapper>
          <Analytics />
          <SpeedInsights />
          <GlobalStyles />
        </AppBackground>
      </StyledComponentsRegistry>
    </html>
  );
}
